backend:
  name: github
  repo: ahmet2c1k/masaloku
  branch: main
  base_url: https://sstatic1.decapcms.org

media_folder: "images"
public_folder: "images"

collections:
  - name: "masallar"
    label: "📖 Masallar"
    files:
      - file: "masallar.json"
        label: "Tüm Masallar Listesi"
        name: "masallar_listesi"
        fields:
          - label: "Masallar"
            name: "masallar"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "number", value_type: "int" }
              - { label: "Başlık", name: "baslik", widget: "string" }
              - { label: "Kategori", name: "kategori", widget: "select", options: ["Hayvanlar", "Sihirli", "Uyku"] }
              - { label: "Kapak Resmi", name: "resim", widget: "image" }
              - { label: "Masal Metni", name: "metin", widget: "text" }

  - name: "tekerlemeler"
    label: "⚡ Tekerlemeler"
    files:
      - file: "tekerlemeler.json"
        label: "Tüm Tekerlemeler Listesi"
        name: "tekerlemeler_listesi"
        fields:
          - label: "Tekerlemeler"
            name: "tekerlemeler"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "number", value_type: "int" }
              - { label: "Başlık", name: "baslik", widget: "string" }
              - { label: "Kapak Resmi", name: "resim", widget: "image" }
              - { label: "Tekerleme Metni", name: "metin", widget: "text" }
